### ISSUE TITLE
Nightly build shows 404 on startup

### ISSUE THREAD

**Issue by russorat** [influxdata/platform#2050]
Just loaded up the nightly and get a 404 on startup: http://dl.influxdata.com/flux/nightlies/influx_nightly_darwin_amd64.tar.gz

![image](https://user-images.githubusercontent.com/4805997/50241219-cc012a80-037b-11e9-8c6c-8ece30f28776.png)

**Comment by mark-rushakoff** [comment]
Possibly fixed by #2060?

**Comment by BondAnthony** [comment]
@mark-rushakoff #2060 didn't fix the issue. Master as of an hour ago is still returning 404.

**Comment by BondAnthony** [comment]
The nightly build do not produce the expected results. Binary is still returning a 404

**Comment by nathanielc** [comment]
This is working for me now.

**Comment by BondAnthony** [comment]
@nathanielc what `make` command are you running? The nightly builds use goreleaser which runs `make generate` before executing the required `go build` commands for each architecture. `make nightly` should cross compile for the other architecture and include the assets for each binary. Right now it appears assets are only being included with the binary of the running system.
